name:                HaskellSnippets
version:             0.1.0.0
github:              "jeikelboom/HaskellSnippets"
license:             BSD3
author:              "Johan Eikelboom"
maintainer:          "johan@jeikelboom.eu"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hobby

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeikelboom/HaskellSnippets#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit

library:
  source-dirs: src

executables:
  HaskellSnippets-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellSnippets

tests:
  HaskellSnippets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellSnippets
